language: ruby
rvm:
  - 2.1.2
  - 2.0.0
  - 1.9.3
  - jruby-19mode
  - rbx-2
bundler_args: --without dev_env
jdk:
  oraclejdk7
script: 'bundle exec rake features spec rubocop'
branches:
  only:
    - master
    - testing