language: ruby
rvm:
  - 2.1.2
  - 2.0.0
  - 1.9.3
  - jruby-19mode
  - rbx-2
before_install:
  - gem update --system
bundler_args: --binstubs --without dev_env
jdk:
  oraclejdk7
script: 'bundle exec rake features spec'
branches:
  only:
    - master
    - testing